version: "3"
services:
  test:
    build: .
    ports:
      - "3050:3050"
    container_name: widget
    environment:
      NODE_ENV: test
      PORT: 3050
      NODE_PATH: app/src
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      MONGO_PORT_27017_TCP_ADDR: mongo
      GATEWAY_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:3050
      FASTLY_ENABLED: "false"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
    command: test
    depends_on:
      - mongo

  mongo:
    image: mongo:3.4
    command: --smallfiles
    ports:
      - "27017"
