apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: widget
    app: rw
  name: widget
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: widget
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - apps
      containers:
      - name: widget
        image: vizzuality/widget
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.25"
            memory: "256M"
          limits:
            cpu: "1"
            memory: "512M"
        args:
          - start
        env:
          - name: PORT
            value: "3050"
          - name: NODE_ENV
            value: prod
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://widget.default.svc.cluster.local:3050
          - name: MONGO_URI
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: WIDGET_MONGO_URI
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: CARTODB_USER
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CARTODB_USER
          - name: FASTLY_APIKEY
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: FASTLY_APIKEY
          - name: FASTLY_SERVICEID
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: FASTLY_SERVICEID

        ports:
          - containerPort: 3050
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthcheck
            port: 3050
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /healthcheck
            port: 3050
          failureThreshold: 3
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15

      restartPolicy: Always
